# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 863ed499cf03860bf08a9031044664e47333eb7acccd2b43386ee6529ff453fce84d19a4bda377385fe5165e2177d31df608dd024e5c288b64a114f8983f1843

test:
  secret_key_base: 9affe7f85960603dcca058abb279c5fa7db8713fd5082cb8d127b6c438f1dd0c7d7c2e4a6c28419ba66d1559c684ba9337205899d25c01b1bc3116bc1cb717df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
